name: Publish and Update Service

on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
      - main
  # Allows users to trigger the workflow manually from the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: environment
        default: dev
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Specify the environment to pull secrets and variables from
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configures DuploCloud and the host cloud, for example, AWS
      - name: Duplo Setup
        uses: duplocloud/actions/setup@v0.0.5
        with:
          account-id: ${{ secrets.CLOUD_ACCOUNT }}  # This is pulled from the 'demo' environment
          credentials: ${{ secrets.CLOUD_CREDENTIALS }}  # From the 'demo' environment

      - name: Debug Selected Environment
        run: echo "Environment: demo is selected"

      # Optionally, if you need to use environment variables as well, set them like this:
      env:
        DUPLO_HOST: ${{ vars.DUPLO_HOST }}  # This comes from the 'demo' environment
        DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}  # This secret comes from the 'demo' environment
        DUPLO_TENANT: demo
