name: Branch-Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment to deploy. For dev environment select develop, to deploy in production select master, to deploy in qa environment select qa
        options:
          - demo
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment-specific secrets
      - name: Duplo Setup
        uses: duplocloud/actions/setup@v0.0.5
        with:
          account-id: ${{ secrets.CLOUD_ACCOUNT }}
          credentials: ${{ secrets.CLOUD_CREDENTIALS }}

      - name: Debug Selected Environment
        run: echo "Selected Environment: ${{ github.event.inputs.environment }}"
