name: Publish and Update Service

on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
      - main
  # Allows users to trigger the workflow manually from the GitHub UI
  workflow_dispatch:
    inputs:
      environment: demo
      # image:
      #   description: The full image URI
      #   type: string
      #   required: true

  # Allows other workflows to use this workflow and its outputs
  workflow_call:
    # outputs:
      # image:
      #   description: The URI of the image
      #   value: ${{ jobs.build_image.outputs.image }}
    secrets:
      DUPLO_TOKEN:
        description: The token to use for DuploCloud API calls
        required: true
env:
  DUPLO_HOST: ${{ vars.DUPLO_HOST }}
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  DUPLO_TENANT: demo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Configures DuploCloud and the host cloud, for example, AWS
      - name: Duplo Setup
        uses: duplocloud/actions/setup@v0.0.5
        with:
          account-id: ${{ vars.CLOUD_ACCOUNT }}
          credentials: ${{ vars.CLOUD_CREDENTIALS }}
